<?php

namespace AppBundle\Repository;

/**
 * charactersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class charactersRepository extends \Doctrine\ORM\EntityRepository
{
}
